### ISSUE TITLE
Inference issues

### ISSUE THREAD

**Issue by TwilightArchon** [wooseoklee4/AP-BSN#17]
Hello! Thanks for your excellent work!
I'm running inference on a single image cropped from a video, and it worked just fine.
However, I modified the base.py to let the model denoise a video, and there is cuda out of memory even if I cropped it to 512 * 512, while running on a single image of size 2688*1520 worked just fine. I extracted the frames from the video using cv2, and tried to denoise each frame using the model, but I got cuda out of memory. Do you have an idea of why there is cuda out of memory on the same image size, and one does not have the out of memory issue?

**Comment by wooseoklee4** [comment]
Hi, sorry for the late reply.

I think there would be a difference on the input image size, assume that there is no modification on the model.
Did you check the input image shape or try to denoise frames once at a time?

Best

**Comment by TwilightArchon** [comment]
Thank you! The problem is solved, instead of directly calling the video denoising method, I put it into "test" function in trainer, and it worked fine, and I have no idea what's the difference, since I called "before test" function.
